repos:
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.3
    hooks:
    -   id: autopep8

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
    -   id: isort

-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: check-merge-conflict
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: flake8
        args: [--max-line-length=120]

